GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjIyOTY3OTkwfQ.MXt_JByDS32nDCb_FA0saS0rpVNC9vY7z4KHT9NG2NQ

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Jim"
}